export const ERROR = "ERROR";
export const RESET_PROFILE = "RESET_PROFILE";
export const CONFIGURE = "CONFIGURE";
export const TRANSACTION_FINISHED = "TRANSACTION_FINISHED";
// #Accounts
export const CHANGE_EVENT = "CHANGE";

export const CONNECTION_CONNECTED = "CONNECTION_CONNECTED";
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED";

